### GET request to example server
## findByEmail
GET http://localhost:3000/api/v1/auth/query?email=prueba3@gmail.com

###
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "ricardo@gmail.com",
  "password": ""
}
